=== sciencehistory/scihist_digicoll/lib/ohms/ohms.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="https://www.weareavp.com/nunncenter/ohms" xmlns="https://www.weareavp.com/nunncenter/ohms/ohms.xsd" version="5.4" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:element name="ROOT">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="record" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="version" type="xs:decimal" minOccurs="1" maxOccurs="1" />
                            <xs:element name="date" minOccurs="1" maxOccurs="1">
                                <xs:complexType>
                                    <xs:attribute name="value" type="xs:string" />
                                    <xs:attribute name="format" type="xs:string" />
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="date_nonpreferred_format" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="cms_record_id" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="title" type="xs:string" minOccurs="1" maxOccurs="1" />
                            <xs:element name="accession" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="duration" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="collection_id" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="collection_name" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="series_id" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="series_name" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="repository" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="funding" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="repository_url" minOccurs="0" maxOccurs="1" />
                            <xs:element name="subject" minOccurs="0" maxOccurs="unbounded" type="xs:string" />
                            <xs:element name="keyword" minOccurs="0" maxOccurs="unbounded" type="xs:string" />
                            <xs:element name="interviewee" minOccurs="0" maxOccurs="unbounded" type="xs:string" />
                            <xs:element name="interviewer" minOccurs="0" maxOccurs="unbounded" type="xs:string" />
                            <xs:element name="format" minOccurs="0" maxOccurs="unbounded" type="xs:string" />
                            <xs:element name="file_name" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="sync" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="sync_alt" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="transcript_alt_lang" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="translate" minOccurs="0" maxOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0" />
                                        <xs:maxInclusive value="1" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="media_id" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="media_url" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="mediafile" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="host" minOccurs="0" maxOccurs="1">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="Avalon" />
                                                    <xs:enumeration value="Aviary" />
                                                    <xs:enumeration value="Brightcove" />
                                                    <xs:enumeration value="Kaltura" />
                                                    <xs:enumeration value="SoundCloud" />
                                                    <xs:enumeration value="Vimeo" />
                                                    <xs:enumeration value="YouTube" />
                                                    <xs:enumeration value="Other" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="avalon_target_domain" type="xs:string" minOccurs="0" maxOccurs="1" />
                                        <xs:element name="host_account_id" type="xs:string" minOccurs="0" maxOccurs="1" />
                                        <xs:element name="host_player_id" type="xs:string" minOccurs="0" maxOccurs="1" />
                                        <xs:element name="host_clip_id" type="xs:string" minOccurs="0" maxOccurs="1" />
                                        <xs:element name="clip_format" minOccurs="0" maxOccurs="1">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="audio" />
                                                    <xs:enumeration value="video" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="kembed" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="language" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="user_notes" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="index" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="point" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="time" type="xs:int" minOccurs="0" maxOccurs="1" />
                                                    <xs:element name="title" type="xs:string" minOccurs="0" maxOccurs="1" />
                                                    <xs:element name="title_alt" type="xs:string" minOccurs="0" maxOccurs="1" />
                                                    <xs:element name="partial_transcript" type="xs:string" minOccurs="0" maxOccurs="1" />
                                                    <xs:element name="partial_transcript_alt" type="xs:string" minOccurs="0" maxOccurs="1" />
                                                    <xs:element name="synopsis" type="xs:string" minOccurs="0" maxOccurs="1" />
                                                    <xs:element name="synopsis_alt" type="xs:string" minOccurs="0" maxOccurs="1" />
                                                    <xs:element name="keywords" type="xs:string" minOccurs="0" maxOccurs="1" />
                                                    <xs:element name="keywords_alt" type="xs:string" minOccurs="0" maxOccurs="1" />
                                                    <xs:element name="subjects" type="xs:string" minOccurs="0" maxOccurs="1" />
                                                    <xs:element name="subjects_alt" type="xs:string" minOccurs="0" maxOccurs="1" />
                                                    <xs:element name="gpspoints" minOccurs="0" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="gps" minOccurs="0" maxOccurs="1" type="xs:string"></xs:element>
                                                                <xs:element name='gps_zoom'>
		                                                        	<xs:simpleType>
			                                                            <xs:union>
			                                                                <xs:simpleType>
			                                                                    <xs:restriction base='xs:string'>
			                                                                        <xs:length value='0'/>
			                                                                    </xs:restriction>
			                                                                </xs:simpleType>
			                                                                <xs:simpleType>
			                                                                    <xs:restriction base='xs:integer'>
			                                                                    </xs:restriction>
			                                                                </xs:simpleType>
			                                                            </xs:union>
			                                                        </xs:simpleType>
			                                                    </xs:element>
                                                                <xs:element name="gps_text" minOccurs="0" maxOccurs="1" type="xs:string"></xs:element>
                                                                <xs:element name="gps_text_alt" minOccurs="0" maxOccurs="1" type="xs:string"></xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
	                                                </xs:element>
	                                                <xs:element name="hyperlinks" minOccurs="0" maxOccurs="unbounded">
	                                                    <xs:complexType>
	                                                        <xs:sequence>
	                                                            <xs:element name="hyperlink" minOccurs="0" maxOccurs="1" type="xs:string"></xs:element>
	                                                            <xs:element name="hyperlink_text" minOccurs="0" maxOccurs="1" type="xs:string"></xs:element>
	                                                            <xs:element name="hyperlink_text_alt" minOccurs="0" maxOccurs="1" type="xs:string"></xs:element>
	                                                        </xs:sequence>
	                                                    </xs:complexType>
	                                                </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="type" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="rel" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="transcript" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="transcript_alt" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="rights" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="fmt" minOccurs="0" maxOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="audio" />
                                        <xs:enumeration value="video" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="usage" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="userestrict" minOccurs="0" maxOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0" />
                                        <xs:maxInclusive value="1" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="xmllocation" minOccurs="0" maxOccurs="1" />
                            <xs:element name="xmlfilename" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="collection_link" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="series_link" type="xs:string" minOccurs="0" maxOccurs="1" />
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:int" use="required" />
                        <xs:attribute name="dt" type="xs:date" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== sciencehistory/scihist_digicoll/spec/test_support/ohms_xml/empty_ohms.xml
<?xml version="1.0" encoding="UTF-8"?>
<ROOT xmlns="https://www.weareavp.com/nunncenter/ohms" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.weareavp.com/nunncenter/ohms/ohms.xsd"><record id="00089280" dt="2020-04-08"><version>5.4</version><date value="" format="yyyy-mm-dd"/><date_nonpreferred_format>Unknown Date</date_nonpreferred_format><cms_record_id></cms_record_id><title>Oral history interview with Hubert N. Alyea</title><accession>OH0010</accession><duration></duration><collection_id></collection_id><collection_name></collection_name><series_id></series_id><series_name></series_name><repository>Science History Institute</repository><funding></funding><repository_url /><file_name></file_name><sync></sync><sync_alt></sync_alt><transcript_alt_lang></transcript_alt_lang><translate>0</translate><media_id></media_id><media_url>https://scihist-digicoll-production-derivatives.s3.amazonaws.com/combined_audio_derivatives/29028ec1-d42e-44c3-af0c-f7e60078b5e7/combined_5914c48cb298d093a994d9b562119d94.mp3</media_url><mediafile><host>Other</host><avalon_target_domain></avalon_target_domain><host_account_id></host_account_id><host_player_id></host_player_id><host_clip_id></host_clip_id><clip_format>audio</clip_format></mediafile><kembed></kembed><language></language><user_notes></user_notes><type></type><description></description><rel /><transcript>No transcript.</transcript><transcript_alt></transcript_alt><rights></rights><fmt>audio</fmt><usage></usage><userestrict>0</userestrict><xmllocation></xmllocation><xmlfilename></xmlfilename><collection_link></collection_link><series_link></series_link></record></ROOT>

=== sciencehistory/scihist_digicoll/spec/test_support/ohms_xml/legacy/various_gaps.xml
<?xml version="1.0" encoding="UTF-8"?>
<ROOT xmlns="https://www.weareavp.com/nunncenter/ohms" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.weareavp.com/nunncenter/ohms/ohms.xsd"><record id="00089981" dt="2020-05-18"><version>5.4</version><date value="" format="yyyy-mm-dd"/><date_nonpreferred_format>Unknown Date</date_nonpreferred_format><cms_record_id></cms_record_id><title>Fifty-line interview</title><accession>SILENCEISGOLDEN</accession><duration></duration><collection_id></collection_id><collection_name></collection_name><series_id></series_id><series_name></series_name><repository>Science History Institute</repository><funding></funding><repository_url /><interviewee>Miss Piggy</interviewee><interviewer>Kermit the Frog</interviewer><file_name></file_name><sync>1:|1(3)|3(2)|3(3)|7(2)|7(3)|7(8)|7(9)|12(2)|12(3)|14(1)|14(3)|16(1)|16(2)|16(4)|16(5)|20(1)|20(8)|20(9)|21(3)|22(5)|22(6)|22(7)</sync><sync_alt></sync_alt><transcript_alt_lang></transcript_alt_lang><translate>0</translate><media_id></media_id><media_url>https://scihist-digicoll-staging-derivatives.s3.amazonaws.com/combined_audio_derivatives/88fbb7a9-e693-4c7d-9c01-bcfd05fbdae6/combined_099a56d3aae9f6970a10f589f22d2746.mp3</media_url><mediafile><host>Other</host><avalon_target_domain></avalon_target_domain><host_account_id></host_account_id><host_player_id></host_player_id><host_clip_id></host_clip_id><clip_format>audio</clip_format></mediafile><kembed></kembed><language></language><user_notes></user_notes><index></index><type></type><description></description><rel /><transcript>Yes, my father was a petrologist. He graduated from Columbia in 1888.
I feel confident that if he had lived a little later, 
he would have been a physical chemist, because his interests
lay along those lines of physical chemistry. He was not interested
in descriptive geology or paleontology but he wanted to know how
things got there. He was interested in the structure of things.
My father&#039;s first cousin was a professor of chemistry at Vassar College.
She was not a research chemist and she left Vassar to become
president of Connecticut College. That shows a beginning interest
in science.

My father
was a
great believer
in
scientific research,

so I was brought up to believe that that was a great thing to do.
It spread through the family. My brother [Henry DeWolf Smyth]
is a physicist. He was chairman of the physics department here.
Frederic Hastings Smyth, my first cousin on the Smyth side,
took a Ph.D. in physical chemistry at MIT, and was in the
Chemical Warfare Service during the war. As a matter of fact,
he devised the crossed alembics over a benzene ring which
was the symbol of the Chemical Warfare Service that officers
wore on their collars. He went into industry for a year or two
and was with a geophysical lab for a few years. He had independent
means and quit. After studying philosophy and religion, he became
an Episcopal clergyman and founded his own small order.
That was not very scientific.</transcript><transcript_alt></transcript_alt><rights></rights><fmt>audio</fmt><usage></usage><userestrict>0</userestrict><xmllocation></xmllocation><xmlfilename></xmlfilename><collection_link></collection_link><series_link></series_link></record></ROOT>

=== sciencehistory/scihist_digicoll/spec/test_support/ohms_xml/chappelear-ohmsvtt-example.xml
<?xml version="1.0" encoding="UTF-8"?>
<ROOT xmlns="https://www.weareavp.com/nunncenter/ohms" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.weareavp.com/nunncenter/ohms/ohms.xsd">
  <record id="41421" dt="2026-03-27">
    <version>6.0</version>
    <date value="" format="yyyy-mm-dd"/>
    <date_nonpreferred_format/>
    <cms_record_id/>
    <title>Oral history interview with Patsy Stallings Chappelear</title>
    <accession>OH1153</accession>
    <duration>00:00:00</duration>
    <collection_id/>
    <collection_name/>
    <series_id/>
    <series_name/>
    <repository>Science History Institute</repository>
    <funding/>
    <repository_url>sciencehistory</repository_url>
    <interviewee/>
    <interviewer/>
    <format/>
    <file_name/>
    <transcript_alt_lang/>
    <translate>0</translate>
    <media_id/>
    <media_url>https://d3dkjx001zrum8.cloudfront.net/combined_audio_derivatives/e200e270-6108-49ce-a1ab-b879ea68cb2a/combined_b4933a8aba32f395c07dd6ed50429ab0.m4a</media_url>
    <mediafile>
      <host>Other</host>
      <avalon_target_domain/>
      <host_account_id/>
      <host_player_id/>
      <host_clip_id/>
      <clip_format>audio</clip_format>
    </mediafile>
    <kembed/>
    <language/>
    <user_notes/>
    <index>
    </index>
    <type/>
    <description/>
    <rel/>
    <vtt_transcript><![CDATA[WEBVTT

NOTE
TRANSCRIPTION BEGIN

00:00:04.000 --> 00:00:29.000
<v SCHNEIDER>   Okay. So today is Wednesday, January 24, 2024. My name is Sarah Schneider and I am joined by Gayle J. Gibson. We are conducting the first session of an oral history interview with Patsy S. Chappelear at her home in Houston, Texas. Okay. So I know you were born in Burnet, Texas. Or [is it pronounced] Burnet, Texas?

00:00:29.000 --> 00:00:29.000
<v CHAPPELEAR>   Burnet.

00:00:29.000 --> 00:00:39.000
<v SCHNEIDER>   Burnet. And so I’m curious about your childhood, and to start off, if you could talk a little bit about your parents and what they were like, and maybe a little bit about their backgrounds.

00:00:39.000 --> 00:01:31.000
<v CHAPPELEAR>   Well, I was born in 1931 when the [Great] Depression was in the United States. My father [Raymond Dero Stallings] was working as a laborer on the dam for Buchanan Lake. When I was two weeks old, he lost his job, as so many people did. And they packed up everything they owned with me and my older half-brother, ten years older than I, in the sedan and went to my grandmother’s [Serena “Rena” Adams Trainer] house in West Texas [Sonora, Texas]. So that was how we started. There were no jobs. So whenever there was a job opening any place at all in West Texas when I was a baby, my parents would load up and go and go there, and they might work a day or a week or two weeks and then be laid off, and they’d go back to my grandmother’s. And this went on.

00:01:31.000 --> 00:02:28.000
At one point when I was still a very small baby, they went to California and tried working there. My uncles of my mother’s—through my mother’s family—would hop freights there in Sonora, [Texas] and go out and try to work on the dams. You . . . Depression was really, really a hard, hard time. My father had a seventh-grade education. My mother [Cora Burleson “Cody” Trainer Nicks Stallings] had quit in the eleventh grade because she didn’t have shoes to wear to school. So they both valued education very, very much. My older brother [Sammie “Sam” Roy Nicks], during those very early years that I can’t remember, checked in and out of the Sonora [Independent] School District in one year, seven times. That’s what looking for a job during those years meant.

00:02:28.000 --> 00:03:34.000
At any rate, we ended up—when I was starting school we were in Big Spring, Texas again, and I went to a private school. My birthday being in October, somehow or other, they got the money to send me to private school. I don’t know how, but they did. And so I went first grade all to this private school, and I started second grade there in Big Spring. But from that point on, my father was a salesman, a really good one, and he did various things with insurance and other stuff, and we would move and back and forth. And eventually he went into construction business when I was ten years old. But moving around, I went to a total of about ten different elementary schools, so it was quite different. Fortunately, I am very bright, so I didn’t have any problem making straight A’s except for penmanship. Solid C’s. I liked school very much. It was fun.

00:03:34.000 --> 00:04:48.000
I loved going to my grandmother’s in the summertime out in West Texas. The Johnson girls lived up behind her, and we played out under the mesquite trees and used rocks to make our house for our playhouse. And you, you cooked, “cooked” with quote marks around it, the mesquite beans as food for your dolls who lived there. Mesquite beans are very poisonous, so don’t try this. [. . .] Everybody was poor. The story was that when I was the baby, that first year when I was, you know, November came it was Thanksgiving time, my dad took the car and went out to the Federal Reserve and killed two turkeys and tied them under the old car and brought them into town. And that’s what they had for Thanksgiving dinner, wild turkeys. Illegal wild turkeys. I had a lot of cousins and we—had lots of fun with them.

00:04:48.000 --> 00:05:35.000
In ’41, first big event in my life was [the attack on] Pearl Harbor. And we—my family—my older brother and his wife [Wilma Jean Lakey Nicks] and son [Mike Murphy Nicks] and a couple of aunts and two or three uncles, all of these people did construction work, and we all went to Ohio to work on a defense plant. So we were all up there on December the seventh, 1941, Sunday, and my cousins and I and my brother—younger brother [Raymond Donald “Don” Stallings]—had all gone to the movies. In those days, you walked to the movies, and it was perfectly safe to do so any place in the United States.

00:05:35.000 --> 00:06:26.000
As we were walking home, up came two cars with my dad and one of my uncles, and they had heard on the radio about the bombing of Pearl Harbor, and they came to get us. I finally found out what that meant on 9/11 [September 11, 2001]. You have this strong desire to get your progeny and gather them up to yourself and make sure they’re okay. And we went to the house and we had—we were lucky. We had a radio. It was about the size of the placemat and sat on the table, had an oval top like this. And you sat and you looked at the radio and you listened to President [Franklin D.] Roosevelt declare war on the United [States] on . . . .

00:06:26.000 --> 00:07:27.000
I had a cousin [Howard Peters, Jr.] who was at Pearl Harbor, and he was almost like a brother because his mother had been mentally ill and my mother was his official guardian. So he was only sixteen when she signed the papers for him to join—or seventeen—so he was very, very young. His boat was shot out from under him at Pearl Harbor and we didn’t know, you know, for a week or two whether he was all right. But he was. Later on in the war years he was torpedoed off of Africa and he was picked up and survived. The third time he was torpedoed in the Gulf of Mexico and picked up, came to New Orleans, [Louisiana], [got] on a bus and came. At that time we were living in Baytown, Goose Creek, [Texas]. And he got off the bus and got out to where we lived and came up to the door and knocked on the door. My dad went to the door, “Junior!” and fainted. This was the third time.

00:07:27.000 --> 00:08:10.000
I had an aunt [Serena Elizabeth “Pena” Trainer McGuire Siverling] who was a nurse in the army. She was in the Blitz in London, [England]. I had an uncle [James Anderson Nunley] who was a fighter pilot over Germany. I had an uncle [John Allison “Aggie” Trainer] who was in the march through Africa. I had another uncle [James Beryl Shanks] who was a Seabee in the South Pacific and various and sundry others. I’ve forgotten all of them. Not a single one got a purl—a what is it that you get—a Purple Heart. Now one of them got a Silver Star [Medal] and all that kind of stuff. They all survived and came back, which was very unusual for that large a family.

00:08:10.000 --> 00:08:43.000
So there we were in Big Spring when—well, we came back to Houston, [Texas], and I went to school in Goose Creek at that time. And that’s when I was a Girl Scout. And I got to go to a camp—let’s see, there’s Agnes Arnold. I think I went to Agnes Arnold. It’s still a camp here in Houston. We have Girl Scout camps, about three of them. And I got to go to Girl Scout camp one year. That was a highlight of my . . . . It really was something to get to go to camp.

00:08:43.000 --> 00:08:46.000
<v SCHNEIDER>   And what were some of the things that you did at camp?


NOTE
TRANSCRIPTION END

]]></vtt_transcript>
    <rights/>
    <fmt>audio</fmt>
    <usage/>
    <userestrict>0</userestrict>
    <xmllocation>/render.php?cachefile=</xmllocation>
    <xmlfilename/>
    <collection_link/>
    <series_link/>
  </record>
</ROOT>
