=== sciencehistory/scihist_digicoll/lib/ohms/ohms.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="https://www.weareavp.com/nunncenter/ohms" xmlns="https://www.weareavp.com/nunncenter/ohms/ohms.xsd" version="5.4" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:element name="ROOT">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="record" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="version" type="xs:decimal" minOccurs="1" maxOccurs="1" />
                            <xs:element name="date" minOccurs="1" maxOccurs="1">
                                <xs:complexType>
                                    <xs:attribute name="value" type="xs:string" />
                                    <xs:attribute name="format" type="xs:string" />
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="date_nonpreferred_format" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="cms_record_id" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="title" type="xs:string" minOccurs="1" maxOccurs="1" />
                            <xs:element name="accession" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="duration" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="collection_id" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="collection_name" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="series_id" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="series_name" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="repository" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="funding" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="repository_url" minOccurs="0" maxOccurs="1" />
                            <xs:element name="subject" minOccurs="0" maxOccurs="unbounded" type="xs:string" />
                            <xs:element name="keyword" minOccurs="0" maxOccurs="unbounded" type="xs:string" />
                            <xs:element name="interviewee" minOccurs="0" maxOccurs="unbounded" type="xs:string" />
                            <xs:element name="interviewer" minOccurs="0" maxOccurs="unbounded" type="xs:string" />
                            <xs:element name="format" minOccurs="0" maxOccurs="unbounded" type="xs:string" />
                            <xs:element name="file_name" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="sync" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="sync_alt" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="transcript_alt_lang" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="translate" minOccurs="0" maxOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0" />
                                        <xs:maxInclusive value="1" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="media_id" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="media_url" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="mediafile" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="host" minOccurs="0" maxOccurs="1">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="Avalon" />
                                                    <xs:enumeration value="Aviary" />
                                                    <xs:enumeration value="Brightcove" />
                                                    <xs:enumeration value="Kaltura" />
                                                    <xs:enumeration value="SoundCloud" />
                                                    <xs:enumeration value="Vimeo" />
                                                    <xs:enumeration value="YouTube" />
                                                    <xs:enumeration value="Other" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="avalon_target_domain" type="xs:string" minOccurs="0" maxOccurs="1" />
                                        <xs:element name="host_account_id" type="xs:string" minOccurs="0" maxOccurs="1" />
                                        <xs:element name="host_player_id" type="xs:string" minOccurs="0" maxOccurs="1" />
                                        <xs:element name="host_clip_id" type="xs:string" minOccurs="0" maxOccurs="1" />
                                        <xs:element name="clip_format" minOccurs="0" maxOccurs="1">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="audio" />
                                                    <xs:enumeration value="video" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="kembed" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="language" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="user_notes" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="index" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="point" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="time" type="xs:int" minOccurs="0" maxOccurs="1" />
                                                    <xs:element name="title" type="xs:string" minOccurs="0" maxOccurs="1" />
                                                    <xs:element name="title_alt" type="xs:string" minOccurs="0" maxOccurs="1" />
                                                    <xs:element name="partial_transcript" type="xs:string" minOccurs="0" maxOccurs="1" />
                                                    <xs:element name="partial_transcript_alt" type="xs:string" minOccurs="0" maxOccurs="1" />
                                                    <xs:element name="synopsis" type="xs:string" minOccurs="0" maxOccurs="1" />
                                                    <xs:element name="synopsis_alt" type="xs:string" minOccurs="0" maxOccurs="1" />
                                                    <xs:element name="keywords" type="xs:string" minOccurs="0" maxOccurs="1" />
                                                    <xs:element name="keywords_alt" type="xs:string" minOccurs="0" maxOccurs="1" />
                                                    <xs:element name="subjects" type="xs:string" minOccurs="0" maxOccurs="1" />
                                                    <xs:element name="subjects_alt" type="xs:string" minOccurs="0" maxOccurs="1" />
                                                    <xs:element name="gpspoints" minOccurs="0" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="gps" minOccurs="0" maxOccurs="1" type="xs:string"></xs:element>
                                                                <xs:element name='gps_zoom'>
		                                                        	<xs:simpleType>
			                                                            <xs:union>
			                                                                <xs:simpleType>
			                                                                    <xs:restriction base='xs:string'>
			                                                                        <xs:length value='0'/>
			                                                                    </xs:restriction>
			                                                                </xs:simpleType>
			                                                                <xs:simpleType>
			                                                                    <xs:restriction base='xs:integer'>
			                                                                    </xs:restriction>
			                                                                </xs:simpleType>
			                                                            </xs:union>
			                                                        </xs:simpleType>
			                                                    </xs:element>
                                                                <xs:element name="gps_text" minOccurs="0" maxOccurs="1" type="xs:string"></xs:element>
                                                                <xs:element name="gps_text_alt" minOccurs="0" maxOccurs="1" type="xs:string"></xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
	                                                </xs:element>
	                                                <xs:element name="hyperlinks" minOccurs="0" maxOccurs="unbounded">
	                                                    <xs:complexType>
	                                                        <xs:sequence>
	                                                            <xs:element name="hyperlink" minOccurs="0" maxOccurs="1" type="xs:string"></xs:element>
	                                                            <xs:element name="hyperlink_text" minOccurs="0" maxOccurs="1" type="xs:string"></xs:element>
	                                                            <xs:element name="hyperlink_text_alt" minOccurs="0" maxOccurs="1" type="xs:string"></xs:element>
	                                                        </xs:sequence>
	                                                    </xs:complexType>
	                                                </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="type" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="rel" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="transcript" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="transcript_alt" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="rights" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="fmt" minOccurs="0" maxOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="audio" />
                                        <xs:enumeration value="video" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="usage" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="userestrict" minOccurs="0" maxOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0" />
                                        <xs:maxInclusive value="1" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="xmllocation" minOccurs="0" maxOccurs="1" />
                            <xs:element name="xmlfilename" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="collection_link" type="xs:string" minOccurs="0" maxOccurs="1" />
                            <xs:element name="series_link" type="xs:string" minOccurs="0" maxOccurs="1" />
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:int" use="required" />
                        <xs:attribute name="dt" type="xs:date" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== sciencehistory/scihist_digicoll/spec/test_support/ohms_xml/index_hyperlinks_example.xml
<?xml version="1.0" encoding="UTF-8"?>
<ROOT xmlns="https://www.weareavp.com/nunncenter/ohms" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.weareavp.com/nunncenter/ohms/ohms.xsd"><record id="00089262" dt="2020-05-28"><version>5.4</version><date value="" format="yyyy-mm-dd"/><date_nonpreferred_format>Unknown Date</date_nonpreferred_format><cms_record_id></cms_record_id><title>Oral history interview with Roy J. Plunkett</title><accession>OH0037</accession><duration></duration><collection_id>1</collection_id><collection_name></collection_name><series_id></series_id><series_name></series_name><repository>Science History Institute</repository><funding></funding><repository_url /><file_name></file_name><sync>1:|1(54)|8(8)|17(7)|32(4)|40(9)|50(14)|63(6)|74(4)|83(13)|94(3)|103(2)|119(2)|129(11)|138(13)|150(13)|157(8)|172(6)|182(5)|194(15)|206(5)|215(7)|224(12)|235(2)|240(4)|246(3)|263(7)|276(9)|289(10)|299(9)|306(2)|315(1)|322(1)|330(1)|337(12)|347(13)|363(9)|379(16)|389(9)|395(4)|404(1)|413(1)|422(2)|444(5)|454(3)|467(2)|479(9)|497(2)|516(2)|531(5)|542(3)|552(1)|559(7)|569(11)|579(4)|585(5)|592(13)|600(2)|611(12)|620(5)|636(3)|640(1)|646(12)|660(4)|673(1)|673(11)|682(11)|693(2)|703(6)|712(1)|720(1)|726(5)|736(6)|745(7)|755(1)|762(11)|770(1)|775(10)|782(4)|790(13)|801(2)|809(8)|822(9)|830(7)|839(15)|847(14)|858(2)|873(3)|882(4)|890(11)|895(2)|903(7)|912(2)|923(3)|933(2)|939(7)|950(2)|964(8)|974(4)|980(2)|986(10)|996(11)|1002(7)|1012(11)|1024(12)|1035(2)|1046(9)|1055(2)|1066(2)|1082(10)|1091(12)|1108(1)|1116(11)|1123(3)|1133(3)|1145(8)|1152(10)|1160(2)|1171(2)|1183(5)|1193(1)|1201(8)|1213(2)|1220(11)|1230(6)|1239(7)|1246(9)|1258(2)|1272(1)|1277(3)|1289(7)|1297(2)|1311(13)|1321(6)|1331(8)|1338(12)|1351(1)|1351(6)|1357(7)|1368(6)|1376(15)|1387(8)|1400(7)|1412(7)|1425(14)|1436(3)|1446(2)|1454(10)|1464(2)|1471(11)</sync><sync_alt></sync_alt><transcript_alt_lang></transcript_alt_lang><translate>0</translate><media_id></media_id><media_url>https://scihist-digicoll-production-derivatives.s3.amazonaws.com/combined_audio_derivatives/f1a1194b-02cb-43fd-a112-5dc4772adb85/combined_90f7880e92e4d28f6b59d2c666b4662a.mp3</media_url><mediafile><host>Other</host><avalon_target_domain></avalon_target_domain><host_account_id></host_account_id><host_player_id></host_player_id><host_clip_id></host_clip_id><clip_format>audio</clip_format></mediafile><kembed></kembed><language></language><user_notes></user_notes><index><point><time>1</time><title>Pre-Interview Remarks</title><title_alt></title_alt><partial_transcript>BOHNING: [inaudible] Check to make sure that everything is working right.</partial_transcript><partial_transcript_alt></partial_transcript_alt><synopsis></synopsis><synopsis_alt></synopsis_alt><keywords></keywords><keywords_alt></keywords_alt><subjects></subjects><subjects_alt></subjects_alt><gpspoints><gps></gps><gps_zoom></gps_zoom><gps_text></gps_text><gps_text_alt></gps_text_alt></gpspoints><hyperlinks><hyperlink></hyperlink><hyperlink_text></hyperlink_text><hyperlink_text_alt></hyperlink_text_alt></hyperlinks></point><point><time>3473</time><title>DuPont and Tetraethyl Lead</title><title_alt></title_alt><partial_transcript>BOHNING: There are a number of things that are curious to me after this event occurred in April of 1938. Your involvement changed rather quickly.</partial_transcript><partial_transcript_alt></partial_transcript_alt><synopsis></synopsis><synopsis_alt></synopsis_alt><keywords>Alyea, Hubert;Antiknock compounds;Arlington Works (DuPont);Benning, Anthony;Chambers Works (Dupont);Corpus Christi, Texas;DuPont (E.I. du Pont de Nemours &amp; Co.);Emulsion polymerization;Ethyl Corporation;Experimental Station (DuPont);Hall of Fame;Hanford, William E.;Jefferson, Edward G.;John Scott Medal;Joyce, Robert M.;Lewis, Ernest E.;Manhattan Project;McHarness, Robert C.;Patents;Pauley, Jane;Polytetrafluoroethylene (PTFE);Ponsol;Renfrew, Malcolm;Second World War (WWII);Synthetic rubbers;Teflon;Teflon aorta;Tetraethyl lead (TEL);Tetrafluoroethylene (TFE);Thiokol rubbers;Thompson, Virden;U.S. Gasket Company;Wilmington, Delaware;World War II (WWII)</keywords><keywords_alt></keywords_alt><subjects></subjects><subjects_alt></subjects_alt><gpspoints><gps></gps><gps_zoom></gps_zoom><gps_text></gps_text><gps_text_alt></gps_text_alt></gpspoints><hyperlinks><hyperlink>https://digital.sciencehistory.org/works/cf95jc49c</hyperlink><hyperlink_text>Oral history interview with Hubert N. Alyea</hyperlink_text><hyperlink_text_alt></hyperlink_text_alt></hyperlinks><hyperlinks><hyperlink>https://digital.sciencehistory.org/works/g445cf063</hyperlink><hyperlink_text>Oral history interview with William E. Hanford</hyperlink_text><hyperlink_text_alt></hyperlink_text_alt></hyperlinks><hyperlinks><hyperlink>https://digital.sciencehistory.org/works/1n79h560c</hyperlink><hyperlink_text>Oral history interview with Malcolm M. Renfrew</hyperlink_text><hyperlink_text_alt></hyperlink_text_alt></hyperlinks></point></index><type></type><description></description><rel /><transcript>
</transcript><transcript_alt></transcript_alt><rights></rights><fmt>audio</fmt><usage></usage><userestrict>0</userestrict><xmllocation></xmllocation><xmlfilename></xmlfilename><collection_link></collection_link><series_link></series_link></record></ROOT>
